[tools]
bats = "1.12.0"
editorconfig-checker = "3.4.1"
"pipx:pre-commit" = { version = "4.4.0", uvx_args = "--with pre-commit-uv" }
pre-commit = "4.4.0"
shellcheck = "0.11.0"
shfmt = "3.12.0"
uv = "0.9.8"

[settings]
idiomatic_version_file_enable_tools = [
]

[task_config]
includes = [
    "toolbox/scripts",
]
